language: python
python: 2.7
env:
  - TOX_ENV=py34 COVERAGE="true"
  - TOX_ENV=py27 COVERAGE="true"
  - TOX_ENV=docs COVERAGE="false"
install:
  - pip install python-coveralls
  - pip install -r requirements.txt
  - pip install -e .
script:
  - python setup.py test
after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
